# Generated by Django 2.1.5 on 2019-01-16 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FlyBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('departure_date', models.DateTimeField()),
                ('arrival_date', models.DateTimeField()),
                ('departure_place', models.CharField(max_length=100)),
                ('arrival_place', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('is_confirmed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('arrival_date', models.DateTimeField()),
                ('departure_date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('is_confirmed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='clientaccount',
            name='persons',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.Person'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.ClientAccount'),
        ),
        migrations.AddField(
            model_name='booking',
            name='fly_booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.FlyBooking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel_booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.HotelBooking'),
        ),
    ]
